select '{{ ds }}',
'{{ dt_tz_add(execution_date) }}',
'{{ dt_tz_add(execution_date, days=-6) }}',
'{{ dt_tz_add(execution_date, days=0) }}',
'{{ dt_tz_add(execution_date, hours=-1) }}',
'{{ dt_tz_add(execution_date,hours=-1) }}',
'{{ dt_tz_add(next_execution_date) }}',
'{{ dt_tz_add(next_execution_date, days=-1) }}',
'{{ dt_tz_add(next_execution_date, days=-1).replace("-","") }}',
'{{ dt_tz_add(next_execution_date, days=-10) }}',
'{{ dt_tz_add(next_execution_date, days=-14) }}',
'{{ dt_tz_add(next_execution_date, days=-15) }}',
'{{ dt_tz_add(next_execution_date, days=-2) }}',
'{{ dt_tz_add(next_execution_date, days=-21) }}',
'{{ dt_tz_add(next_execution_date, days=-22) }}',
'{{ dt_tz_add(next_execution_date, days=-3) }}',
'{{ dt_tz_add(next_execution_date, days=-30) }}',
'{{ dt_tz_add(next_execution_date, days=-31) }}',
'{{ dt_tz_add(next_execution_date, days=-4) }}',
'{{ dt_tz_add(next_execution_date, days=-7) }}',
'{{ dt_tz_add(next_execution_date, days=-8) }}',
'{{ dt_tz_add(next_execution_date, days=0) }}',
'{{ dt_tz_add(next_execution_date, days=1) }}',
'{{ dt_tz_add(next_execution_date, days=15) }}',
'{{ dt_tz_add(next_execution_date, hours=-1) }}',
'{{ dt_tz_add(next_execution_date, minutes=-30) }}',
'{{ dt_tz_add(next_execution_date,days=-1) }}',
'{{ dt_tz_add(next_execution_date,days=1) }}',
'{{ dt_tz_add(next_execution_date,minutes=-5) }}',
'{{ dt_tz_add_ms(execution_date) }}',
'{{ dt_tz_add_ms(next_execution_date) }}',
'{{ dt_tz_add_ms(next_execution_date, days=-1) }}',
'{{ dt_tz_add_ms(next_execution_date,days=1) }}',
'{{ last_success_dt(ti, hours=-1) }}',
'{{ last_success_dt(ti,days=-1) }}',
'{{ last_success_dt(ti,hours=-1) }}',
'{{ last_success_ts(ti) }}',
'{{ last_success_ts(ti, hours=-1) }}',
'{{ last_success_ts(ti, hours=-3) }}',
'{{ last_success_ts(ti,hours=-1) }}',
'{{ params.days }}',
'{{ params.job_name }}',
'{{ params.pt }}',
'{{ params.s3_path }}',
'{{ params.s3_path_prefix }}',
'{{ params.trader_rank_asset_management_orders_in_days }}',
'{{ ts }}',
'{{ ts_tz_add(execution_date) }}',
'{{ ts_tz_add(execution_date) if params.get('is_ts') == True else  }}',
'{{ dt_tz_add(execution_date) }}',
'{{ ts_tz_add(execution_date, hours=-1) }}',
'{{ ts_tz_add(execution_date, hours=-6) }}',
'{{ ts_tz_add(execution_date, minutes=-0) }}',
'{{ ts_tz_add(execution_date, minutes=-10) }}',
'{{ ts_tz_add(execution_date, minutes=-5) }}',
'{{ ts_tz_add(execution_date, minutes=10) }}',
'{{ ts_tz_add(execution_date,days=-1) }}',
'{{ ts_tz_add(execution_date,hours=-1) }}',
'{{ ts_tz_add(execution_date,hours=-1) if params.get('is_ts') == True else  }}',
'{{ dt_tz_add(execution_date) }}',
'{{ ts_tz_add(next_execution_date) }}',
'{{ ts_tz_add(next_execution_date, hours=-1) }}',
'{{ ts_tz_add(next_execution_date, hours=1) }}',
'{{ ts_tz_add(next_execution_date, minutes=-5) }}',
'{{ ts_tz_add(next_execution_date, minutes=-6) }}',
'{{ ts_tz_add(next_execution_date,minutes=-30) }}',
'{{ ts_tz_add_ms(execution_date) }}',
'{{ ts_tz_add_ms(execution_date, hours=-1) }}',
'{{ ts_tz_add_ms(next_execution_date) }}'

    
'{{ ts_tz_add_ms(execution_date) }}'

redshift: '2023-01-01 01:01:01'::timestamp
starrock: '2023-01-01 01:01:01' -> timestamp ?

'{{ ts_tz_add_ms(execution_date) }}'

unix_timestamp('2023-07-19 16:31:00')*1000